name: syconn
dependencies:
  - python=2.7
  - pip

  - cython
  - numpy
  - matplotlib
  - scipy
  - networkx

  - decorator=4.3.0 # Latest version requires python >= 3.5

  - pip:
    - scikit-learn == 0.17.1
    - future # Required for knossos_utils Python 2/3 compatibility
    - python-snappy == 0.5.1 # Required to write/read overlaycubes and k.zips
    # Despite being named python3, this branch is also compatible with Python 2.7.
    # The master branch requires python >= 3.
    # The py3-compat branch lacks skeleton_utils.py.
    - git+https://github.com/knossos-project/knossos_utils.git@python3
    - git+https://github.com/ELEKTRONN/ELEKTRONN.git
    - -e . --global-option="build_ext"